// svelte-app/src/lib/components/Header.svelte
<script>
  import Logo from './Logo.svelte';
</script>

<header class="sticky top-0 bg-white shadow-sm z-50">
  <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
    <div class="flex justify-between items-center h-16">
      <Logo />
      <nav class="flex gap-6">
        <a
          href="/"
          class="text-gray-700 hover:text-gray-900 font-medium"
        >
          Home
        </a>
        <a
          href="/blog"
          class="text-gray-700 hover:text-gray-900 font-medium"
        >
          Blog
        </a>
      </nav>
    </div>
  </div>
</header>

// next-app/components/Header.tsx
import Link from "next/link";
import { Logo } from "./Logo";

export default function Header() {
  return (
    <header className="bg-white shadow-md sticky top-0 z-50">
      <nav className="max-w-7xl mx-auto px-6 py-4">
        <div className="flex items-center justify-between">
          {/* Logo */}
          <Logo />

          {/* Navigation */}
          <div className="flex items-center space-x-8">
            <Link
              href="/"
              className="text-sm font-medium hover:text-blue-600 duration-300 cursor-pointer"
            >
              Home
            </Link>
            <Link
              href="/blog"
              className="text-sm font-medium hover:text-blue-600 duration-300 cursor-pointer"
            >
              Blog
            </Link>
          </div>
        </div>
      </nav>
    </header>
  );
}
