// angular-app/src/app/components/footer.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-footer',
  standalone: true,
  template: `
    <footer class="bg-gray-900 text-white py-12 mt-20">
      <div class="max-w-6xl mx-auto px-4 text-center">
        <p class="text-gray-400">&copy; 2025 BlogApp. All rights reserved.</p>
      </div>
    </footer>
  `,
})
export class FooterComponent {}

// vite-app/src/components/Footer.tsx
export default function Footer() {
  return (
    <footer className="bg-gray-800 text-white py-8 mt-16">
      <div className="max-w-7xl mx-auto px-6 text-center">
        <p className="text-gray-200">
          &copy; 2025 TechBlog. All rights reserved.
        </p>
      </div>
    </footer>
  );
}
