// vue-app/src/views/BlogListPage.vue
<template>
  <div>
    <!-- Hero Section -->
    <section
      class="py-16"
      style="background: linear-gradient(135deg, #667eea 0%, #764ba2 100%)"
    >
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
        <h1 class="text-4xl font-bold text-white mb-4">Our Blog</h1>
        <p class="text-lg text-white/90">
          Explore all our articles and tutorials
        </p>
      </div>
    </section>

    <!-- Blog Posts Grid -->
    <section class="py-12">
      <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
        <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
          <BlogCard v-for="post in posts" :key="post.slug" :post="post" />
        </div>
      </div>
    </section>
  </div>
</template>

<script setup>
import { blogPosts } from "../lib/blog-data";
import BlogCard from "../components/BlogCard.vue";

const posts = blogPosts;
</script>

// vite-app/src/pages/BlogListPage.tsx
import BlogCard from "../components/BlogCard";
import Footer from "../components/Footer";
import Header from "../components/Header";
import { blogPosts } from "../lib/blog-data";

export default function BlogListPage() {
  return (
    <div className="min-h-screen flex flex-col">
      <Header />

      {/* Page Header */}
      <section className="bg-linear-to-r from-blue-600 to-purple-600 text-white py-16">
        <div className="max-w-7xl mx-auto px-6">
          <div className="text-center">
            <h1 className="text-5xl font-bold mb-4">Our Blog</h1>
            <p className="text-xl text-gray-100">
              Explore our latest articles, tutorials, and insights
            </p>
          </div>
        </div>
      </section>

      {/* Blog Posts Section */}
      <section className="py-16 grow">
        <div className="max-w-7xl mx-auto px-6">
          {/* Blog Grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8">
            {blogPosts.map((post) => (
              <BlogCard key={post.slug} post={post} />
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
